###   ________   ________  ___      ___ ________   ###
###  |\   ___  \|\   __  \|\  \    /  /|\   __  \  ###
###  \ \  \\ \  \ \  \|\  \ \  \  /  / | \  \|\  \  ###
###   \ \  \\ \  \ \  \\\  \ \  \/  / / \ \   __  \  ###
###    \ \  \\ \  \ \  \\\  \ \    / /   \ \  \ \  \  ###
###     \ \__\\ \__\ \_______\ \__/ /     \ \__\ \__\  ###
###      \|__| \|__|\|_______|\|__|/       \|__|\|__|  ###


###   ________  ___  ___  ________  ___      ___ ___  ___      ___ ________  ___  ###
###  |\   ____\|\  \|\  \|\   __  \|\  \    /  /|\  \|\  \    /  /|\   __  \|\  \  ###
###  \ \  \___|\ \  \\\  \ \  \|\  \ \  \  /  / | \  \ \  \  /  / | \  \|\  \ \  \  ###
###  \ \_____  \ \  \\\  \ \   _  _\ \  \/  / / \ \  \ \  \/  / / \ \   __  \ \  \  ###
###    \|____|\  \ \  \\\  \ \  \\  \\ \    / /   \ \  \ \    / /   \ \  \ \  \ \  \____  ###
###      ____\_\  \ \_______\ \__\\ _\\ \__/ /     \ \__\ \__/ /     \ \__\ \__\ \_______\  ###
###     |\_________\|_______|\|__|\|__|\|__|/       \|__|\|__|/       \|__|\|__|\|_______|  ###
###     \|_________|  ###
### MaxBlocks must be in increments of 16 ###
### nova.claim ###
MaxBlocksReg: 32
### nova.claim.vip ###
MaxBlocksVIP: 64
### nova.claim.mvp ###
MaxBlocksMVP: 128
MaxPartySize: 10
AllowPartyMembersPVP: true
Explosions:
  AllExplosionsOff: false
  NoBlockDamageExplosions: true
AllowFire: true
PartyUnnamedPlaceholder: ''
ClaimGui:
  Name: '&bYour Claims'
  Material: 'GRASS_BLOCK'
  MaterialName: '&6%Claim%'
  UseLore: false
  Lore: '&6%Claim%'



